-- REPO oficial (Dropbox-only, com links diretos robustos)
-- Execute no SQL Editor do Supabase.

delete from public.launcher_games
where id = 'repo2';

insert into public.launcher_games (
  id,
  name,
  section,
  description,
  long_description,
  archive_type,
  archive_password,
  checksum_sha256,
  dropbox_shared_url,
  download_url,
  download_urls,
  download_sources,
  install_dir_name,
  launch_executable,
  image_url,
  card_image_url,
  banner_url,
  logo_url,
  developed_by,
  published_by,
  release_date,
  trailer_url,
  steam_app_id,
  gallery,
  genres,
  average_play_time,
  average_achievement,
  size_bytes,
  free,
  exclusive,
  coming_soon,
  enabled,
  sort_order
) values (
  'repo',
  'R.E.P.O.',
  'Catalogo',
  'Build de teste do REPO via Dropbox para validar fluxo profissional de download direto.',
  'Versao de teste para validar download via Dropbox com resiliencia de fontes e retomada.',
  'rar',
  'online-fix.me',
  'c09b27ed29370ea971e6c1e03bca7dc1ff59f73d391c11dd8f0ff8cbb9fd850e',
  'https://www.dropbox.com/scl/fi/SEU_FILE_ID/repo.rar?rlkey=SEU_RLKEY&dl=0',
  'https://www.dropbox.com/scl/fi/SEU_FILE_ID/repo.rar?rlkey=SEU_RLKEY&dl=1',
  '[]'::jsonb,
  '[
    {
      "url": "https://www.dropbox.com/scl/fi/SEU_FILE_ID/repo.rar?rlkey=SEU_RLKEY&dl=1",
      "label": "dropbox-dl1",
      "kind": "dropbox",
      "priority": 5
    },
    {
      "url": "https://www.dropbox.com/scl/fi/SEU_FILE_ID/repo.rar?rlkey=SEU_RLKEY&raw=1",
      "label": "dropbox-raw1",
      "kind": "dropbox",
      "priority": 6
    },
    {
      "url": "https://dl.dropboxusercontent.com/scl/fi/SEU_FILE_ID/repo.rar?rlkey=SEU_RLKEY",
      "label": "dropbox-direct",
      "kind": "dropbox",
      "priority": 8
    }
  ]'::jsonb,
  'REPO',
  E'REPO\\REPO.EXE',
  'https://imgur.com/CkC4BWy.png',
  'https://imgur.com/CkC4BWy.png',
  'https://imgur.com/CkC4BWy.png',
  'https://imgur.com/BLXTkyr.png',
  'semiwork',
  'semiwork',
  '26 Feb 2025',
  'https://www.youtube.com/watch?v=oSfoK8eSeD8',
  3241660,
  '[
    "https://imgur.com/CkC4BWy.png",
    "https://imgur.com/3XnsrX0.png",
    "https://imgur.com/vwa15yb.png"
  ]'::jsonb,
  '["Horror","Co-op","Action","Survival"]'::jsonb,
  '16hs',
  '27%',
  951972810,
  false,
  false,
  false,
  true,
  10
)
on conflict (id) do update
set
  name = excluded.name,
  section = excluded.section,
  description = excluded.description,
  long_description = excluded.long_description,
  archive_type = excluded.archive_type,
  archive_password = excluded.archive_password,
  checksum_sha256 = excluded.checksum_sha256,
  dropbox_shared_url = excluded.dropbox_shared_url,
  download_url = excluded.download_url,
  download_urls = excluded.download_urls,
  download_sources = excluded.download_sources,
  install_dir_name = excluded.install_dir_name,
  launch_executable = excluded.launch_executable,
  image_url = excluded.image_url,
  card_image_url = excluded.card_image_url,
  banner_url = excluded.banner_url,
  logo_url = excluded.logo_url,
  developed_by = excluded.developed_by,
  published_by = excluded.published_by,
  release_date = excluded.release_date,
  trailer_url = excluded.trailer_url,
  steam_app_id = excluded.steam_app_id,
  gallery = excluded.gallery,
  genres = excluded.genres,
  average_play_time = excluded.average_play_time,
  average_achievement = excluded.average_achievement,
  size_bytes = excluded.size_bytes,
  free = excluded.free,
  exclusive = excluded.exclusive,
  coming_soon = excluded.coming_soon,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order;
