-- REPO oficial (Drive only, com confirmacao automatica)
-- Execute no SQL Editor do Supabase.

delete from public.launcher_games
where id = 'repo2';

insert into public.launcher_games (
  id,
  name,
  section,
  description,
  long_description,
  archive_type,
  archive_password,
  checksum_sha256,
  download_url,
  download_urls,
  download_sources,
  google_drive_file_id,
  install_dir_name,
  launch_executable,
  image_url,
  card_image_url,
  banner_url,
  logo_url,
  developed_by,
  published_by,
  release_date,
  trailer_url,
  gallery,
  genres,
  average_play_time,
  average_achievement,
  size_bytes,
  free,
  exclusive,
  coming_soon,
  enabled,
  sort_order
) values (
  'repo',
  'R.E.P.O.',
  'Catalogo',
  'Build de teste do REPO via Google Drive usercontent para validar fluxo de confirmacao automatica de arquivo grande.',
  'Versao de teste para validar download via Google Drive com pagina de aviso de virus e confirmacao automatica no launcher.',
  'rar',
  'online-fix.me',
  'c09b27ed29370ea971e6c1e03bca7dc1ff59f73d391c11dd8f0ff8cbb9fd850e',
  'https://drive.usercontent.google.com/download?id=1zDiy1yX_uuKgKIeIj4vmkgCa0p-qtHyu&export=download&authuser=0',
  '[]'::jsonb,
  '[
    {
      "url": "https://drive.usercontent.google.com/download?id=1zDiy1yX_uuKgKIeIj4vmkgCa0p-qtHyu&export=download&authuser=0",
      "label": "driveusercontent-repo",
      "kind": "google-drive",
      "priority": 5
    },
    {
      "url": "https://drive.usercontent.google.com/download?id=1zDiy1yX_uuKgKIeIj4vmkgCa0p-qtHyu&export=download&authuser=0&confirm=t",
      "label": "driveusercontent-confirm",
      "kind": "google-drive",
      "priority": 6
    },
    {
      "url": "https://drive.google.com/uc?export=download&id=1zDiy1yX_uuKgKIeIj4vmkgCa0p-qtHyu",
      "label": "drive-uc-fallback",
      "kind": "google-drive",
      "priority": 8
    }
  ]'::jsonb,
  '1zDiy1yX_uuKgKIeIj4vmkgCa0p-qtHyu',
  'REPO',
  E'REPO\\REPO.EXE',
  'https://imgur.com/CkC4BWy.png',
  'https://imgur.com/CkC4BWy.png',
  'https://imgur.com/CkC4BWy.png',
  'https://imgur.com/BLXTkyr.png',
  'semiwork',
  'semiwork',
  '26 Feb 2025',
  'https://www.youtube.com/watch?v=oSfoK8eSeD8',
  '[
    "https://imgur.com/CkC4BWy.png",
    "https://imgur.com/3XnsrX0.png",
    "https://imgur.com/vwa15yb.png"
  ]'::jsonb,
  '["Horror","Co-op","Action","Survival"]'::jsonb,
  '16hs',
  '27%',
  951972810,
  false,
  false,
  false,
  true,
  10
)
on conflict (id) do update
set
  name = excluded.name,
  section = excluded.section,
  description = excluded.description,
  long_description = excluded.long_description,
  archive_type = excluded.archive_type,
  archive_password = excluded.archive_password,
  checksum_sha256 = excluded.checksum_sha256,
  download_url = excluded.download_url,
  download_urls = excluded.download_urls,
  download_sources = excluded.download_sources,
  google_drive_file_id = excluded.google_drive_file_id,
  install_dir_name = excluded.install_dir_name,
  launch_executable = excluded.launch_executable,
  image_url = excluded.image_url,
  card_image_url = excluded.card_image_url,
  banner_url = excluded.banner_url,
  logo_url = excluded.logo_url,
  developed_by = excluded.developed_by,
  published_by = excluded.published_by,
  release_date = excluded.release_date,
  trailer_url = excluded.trailer_url,
  gallery = excluded.gallery,
  genres = excluded.genres,
  average_play_time = excluded.average_play_time,
  average_achievement = excluded.average_achievement,
  size_bytes = excluded.size_bytes,
  free = excluded.free,
  exclusive = excluded.exclusive,
  coming_soon = excluded.coming_soon,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order;
